server:
  port: 8091

spring:
  # 配置mysql数据源
  datasource:
    # 德鲁伊的数据连接池
    druid:
      username: root
      password: root
      url: jdbc:mysql://192.168.177.234:3306/stock_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.jdbc.Driver
      # 初始化时建立物理连接的个数。初始化发生在显示调用 init 方法，或者第一次 getConnection 时
      initialSize: 6
      # 最小连接池数量
      minIdle: 2
      # 最大连接池数量
      maxActive: 20
      # 获取连接时最大等待时间，单位毫秒。配置了 maxWait 之后，缺省启用公平锁，
      # 并发效率会有所下降，如果需要可以通过配置 useUnfairLock 属性为 true 使用非公平锁。
      maxWait: 60000
# 配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml # 配置加载mapper的资源
  type-aliases-package: com.daily.stock.pojo.entity # 批量给实体类取别名，方便xml直接使用别名，避免冗余配置
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 通过mybatis执行的sql语句以日志的方式输出到终端

#  type-aliases-package 的作用
#  1. 简化类型映射
#  在 MyBatis 的 XML 配置文件中，类型映射通常需要指定完整的类名。例如，在映射器文件中，你可能需要指定一个 Java 类的全限定名：
#     <resultMap id="userResultMap" type="com.example.model.User"> </resultMap>
#  使用 type-aliases-package 后，MyBatis 会自动为指定包下的所有类生成类型别名，从而简化类型映射：
#     <resultMap id="userResultMap" type="User"> </resultMap>


# pagehelper配置
pagehelper:
  helper-dialect: mysql #指定分页数据库类型（方言）
  reasonable: true #合理查询超过最大页，则查询最后一页
  # 比如总页数是100，当查询101页时，自动查询最后一页，也就是100，当查询-1页时，默认查询第一页

DailyIndex:
  jwt:
    privateKeyPath: E:\DailyIndexProject\rsa-key\rsa-key
    publicKeyPath: E:\DailyIndexProject\rsa-key\rsa-key.pub
    expire: 30